### ISSUE TITLE
Imagej stack odd edges when XY shift

### ISSUE THREAD

**Issue by 7rebor** [tischi/fiji-plugin-imageRegistration#10]
If an XY transformation is performed there is some sort of interpolation of pixels from the edge of the image to the edge of the canvas. See the image below:

![image](https://user-images.githubusercontent.com/34678833/35342729-b6102360-0120-11e8-8bd5-cc45d77faa0e.png)

It might be better to leave that space blank, unless it is intended?

**Comment by tischi** [comment]
It just extends the image with the pixel value that was at the border.
We could also make it black. You think that'll be better?

**Comment by 7rebor** [comment]
I think that would be a better idea, reduces spurious analysis results if doing some sort of basic segmentation (not trained) or threshold-based analysis.

**Comment by imagejan** [comment]
While it's fine to use an `OutOfBoundsBorder` strategy (i.e. `Views.extendBorder`) for the image *filter* steps:

https://github.com/tischi/fiji-plugin-imageRegistration/blob/1c426bb227603124c15edbfacb589a58527ddd71/src/main/java/de/embl/cba/registration/filter/ImageFilterGauss.java#L42

https://github.com/tischi/fiji-plugin-imageRegistration/blob/db73f6dc412a7a18d475e28ec08a5be9b78bc842/src/main/java/de/embl/cba/registration/filter/ImageFilterDog.java#L40

I would definitely opt for `Views.extendZero` here:

https://github.com/tischi/fiji-plugin-imageRegistration/blob/c560353e7851024e9bf378d9f62dfa98d34fbeed/src/main/java/de/embl/cba/registration/InputViews.java#L54

or make it a user-definable option (e.g. also allow `OutOfBoundsConstantValue` with `min` or `max` of the image).

**Comment by tischi** [comment]
@imagejan  Thanks for looking so deeply into the code!

I changed it such that "internally" for doing the math in terms of registration it always uses extendBorder (there were also other places than the one you found), e.g. here:

https://github.com/tischi/fiji-plugin-imageRegistration/blob/1c426bb227603124c15edbfacb589a58527ddd71/src/main/java/de/embl/cba/registration/Registration.java#L156

...but for generation of the final output it now always uses zeroing.

I hope that's fine in general as I would like to avoid too many options.

Please Update Fiji and see if it works for you.

**Comment by 7rebor** [comment]
This works fine, I get zeros at the edges of my images, and the image is increased in size to fit any transformation. Thanks!
